[package]
name = "cargo-blinkest"
version = "0.1.0"
authors = ["Bartosz Zbytniewski <bartosz.zbytniewski.dev@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.6"
transition = { path = "../transition", version = "0.2.0" }
