[package]
name = "cargo-blinc"
version = "0.2.0"
authors = ["Bartosz Zbytniewski <bartosz.zbytniewski.dev@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.6"
transition = { path = "../transition", version = "0.2.0" }
toml = "0.5"
serde = "1.0.104"
serde_derive = "1.0.104"
clap = "2.33.0"
