[package]
name = "blinkerst"
version = "0.1.0"
authors = ["Bartosz Zbytniewski <bartosz.zbytniewski.dev@gmail.com>"]
edition = "2018"

[dependencies]
blinkrs = "0.2.1"
lazy_static = "1.4.0"
failure = "0.1.6"
