[package]
name = "cargo-blinc"
version = "0.4.0"
authors = ["Bartosz Zbytniewski <bartosz.zbytniewski.dev@gmail.com>"]
description = "Notifies about commands exit code using LED light"
keywords = ["blink(1)", "blink", "notify"]
license = "MIT/Apache-2.0"
readme = "README.md"
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
repository = "https://github.com/devzbysiu/cargo-blinc"
homepage = "https://github.com/devzbysiu/cargo-blinc"
documentation = "https://docs.rs/cargo-blinc"
edition = "2018"

[dependencies]
failure = "0.1.6"
transition = { path = "../transition", version = "1.0.0" }
toml = "0.5"
serde = "1.0.104"
serde_derive = "1.0.104"
clap = "2.33.0"
log = "0.4.8"
env_logger = "0.7.1"

[dev-dependencies]
assert_cmd = "0.12.0"
predicates = "1.0.2"
serial_test = "0.3.2"
