name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install libusb-1.0
      run: sudo apt-get install libusb-1.0

    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        path: ./cargo-blinc

    - name: Checkout transition
      uses: actions/checkout@v2
      with:
        repository: devzbysiu/transition
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: ./transition

    - uses: Swatinem/rust-cache@v1

    - name: Run cargo-make
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: davidB/rust-cargo-make@v1
    - name: Run tests
      run: cd ./cargo-blinc && cargo make --profile ci all
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

